# Generated by Django 5.0.4 on 2025-07-13 15:27

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), accounts.validators.FileSizeValidator(max_size_mb=6)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), accounts.validators.FileSizeValidator(max_size_mb=6)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), accounts.validators.FileSizeValidator(max_size_mb=6)]),
        ),
    ]
