# Generated by Django 5.0.4 on 2025-07-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventpost_eventlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='text',
            field=models.TextField(error_messages={'max_length': 'Text cannot be more than 300 characters.'}, max_length=300),
        ),
    ]
