# Generated by Django 5.0.4 on 2025-12-24 11:07

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image1',
            field=models.ImageField(blank=True, default='event_images/37.jpg', upload_to='event_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), accounts.validators.FileSizeValidator(max_size_mb=6)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image2',
            field=models.ImageField(blank=True, default='event_images/37.jpg', upload_to='event_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), accounts.validators.FileSizeValidator(max_size_mb=6)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image3',
            field=models.ImageField(blank=True, default='event_images/37.jpg', upload_to='event_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif']), accounts.validators.FileSizeValidator(max_size_mb=6)]),
            preserve_default=False,
        ),
    ]
