# Generated by Django 5.0.4 on 2025-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_eventparticipation_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='status',
            field=models.CharField(choices=[('Will go', 'Will go'), ('Maybe', 'Maybe'), ('Not going', 'Not going')], max_length=20),
        ),
    ]
