# Generated by Django 5.0.4 on 2025-07-11 10:07

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[accounts.validators.FileSizeValidator(max_size_mb=5)]),
        ),
    ]
