# Generated by Django 5.0.4 on 2025-07-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
