# Generated by Django 5.0.4 on 2025-07-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appuser_failed_login_attempts_appuser_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
