# Generated by Django 5.0.4 on 2025-08-15 13:02

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appuser_account_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[accounts.validators.FileSizeValidator(max_size_mb=9)]),
        ),
    ]
